Fix build errors
Having cloned the repo for the first time in three years, I couldn't
even build it. Here's what I did:

    💲 node --version
    v14.17.5

    💲 npm ci
    […]

    💲 npm run build
    […]
    src/read.ts:5:64 - error TS2304: Cannot find name 'require'.

    5 const extractComments: (s: string) => ReadonlyArray<Comment> = require("extract-comments");
                                                                     ~~~~~~~

    src/read.ts:77:50 - error TS2339: Property 'trimRight' does not exist on type 'string'.

    77         return Right({ key, value: value ? value.trimRight() : true } as Entry);
                                                        ~~~~~~~~~

    src/stringify.ts:45:7 - error TS2339: Property 'trimRight' does not exist on type 'string'.

    45     ).trimRight(); // no trailing whitespace on boolean tags
             ~~~~~~~~~
    […]

📝 src/extract-comments.d.ts
📝 src/read.ts

    💲 git show --oneline --stat
    2c303c7 (HEAD -> fix-build-errors) Import extract-comments with `import`
     src/extract-comments.d.ts | 9 +++++++++
     src/read.ts               | 9 +--------
     2 files changed, 10 insertions(+), 8 deletions(-)

    💲 npm run build
    […]
    src/read.ts:70:50 - error TS2339: Property 'trimRight' does not exist on type 'string'.

    70         return Right({ key, value: value ? value.trimRight() : true } as Entry);
                                                        ~~~~~~~~~

    src/stringify.ts:45:7 - error TS2339: Property 'trimRight' does not exist on type 'string'.

    45     ).trimRight(); // no trailing whitespace on boolean tags
             ~~~~~~~~~
    […]

📝 src/read.ts
📝 src/stringify.ts

    💲 git show --oneline --stat
    94691b6 (HEAD -> fix-build-errors) Use trimEnd instead of trimRight
     src/read.ts      | 2 +-
     src/stringify.ts | 2 +-
     2 files changed, 2 insertions(+), 2 deletions(-)

    💲 npm run build
    […]
    src/read.ts:70:50 - error TS2339: Property 'trimEnd' does not exist on type 'string'.

    70         return Right({ key, value: value ? value.trimEnd() : true } as Entry);
                                                        ~~~~~~~

    src/stringify.ts:45:7 - error TS2339: Property 'trimEnd' does not exist on type 'string'.

    45     ).trimEnd(); // no trailing whitespace on boolean tags
             ~~~~~~~
    […]

📝 tsconfig.json

    💲 git show --oneline --stat
    8b58df6 (HEAD -> fix-build-errors) Add ES2019.String in 'lib' in tsconfig.json
     tsconfig.json | 2 +-
     1 file changed, 1 insertion(+), 1 deletion(-)

    💲 npm run build
    […]
    tsconfig.json:14:13 - error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'esnext', 'dom', 'dom.iterable', 'webworker', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'esnext.array', 'esnext.asynciterable'.

    14             "ES2019.String", "es2018", "es2016.array.include"
                   ~~~~~~~~~~~~~~~

    src/read.ts:70:50 - error TS2339: Property 'trimEnd' does not exist on type 'string'.

    70         return Right({ key, value: value ? value.trimEnd() : true } as Entry);
                                                        ~~~~~~~

    src/stringify.ts:45:7 - error TS2339: Property 'trimEnd' does not exist on type 'string'.

    45     ).trimEnd(); // no trailing whitespace on boolean tags
             ~~~~~~~
    […]

    💲 npm install --save-dev typescript@3
    npm WARN ts-jest@23.0.1 requires a peer of typescript@2.x but none is installed. You must install peer dependencies yourself.

    + typescript@3.9.10
    […]

    💲 npm run build
    […]
    > renamer --force --find "/\.js$/" --replace ".mjs" "dist/**"

    Cannot find module 'default'
    Require stack:
    - /[…]/userscript-metadata/node_modules/load-module/index.js
    - /[…]/userscript-metadata/node_modules/command-line-plugin/index.js
    - /[…]/userscript-metadata/node_modules/renamer/lib/cli-app.js
    - /[…]/userscript-metadata/node_modules/renamer/bin/cli.js

    renamer

      Rename files in bulk.

    Synopsis

      $ renamer [options] [file ...]

    […]

      For detailed instructions, visit https://github.com/75lb/renamer

    💲 npm install --save-dev renamer
    npm WARN ts-jest@23.0.1 requires a peer of typescript@2.x but none is installed. You must install peer dependencies yourself.

    + renamer@1.1.4
    […]

    💲 git show --oneline --stat
    693f3e9 (HEAD -> fix-build-errors) Upgrade TypeScript and renamer
     package-lock.json | 2792 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------------------------
     package.json      |    4 +-
     2 files changed, 1381 insertions(+), 1415 deletions(-)

    💲 npm run build
    […]

    💲 npm test
    […]
     PASS  __test__/read.test.ts
     PASS  __test__/validation.test.ts
     PASS  __test__/stringify.test.ts
     PASS  __test__/main.test.ts
     PASS  __test__/data.test.ts
     PASS  __test__/functions.test.ts

    Test Suites: 6 passed, 6 total
    Tests:       54 passed, 54 total
    Snapshots:   0 total
    Time:        2.076s
    Ran all test suites.

    💲 npm install --save-dev ts-jest
    + ts-jest@23.10.5
    […]

    💲 npm test
    […]
     PASS  __test__/stringify.test.ts
     PASS  __test__/read.test.ts
     PASS  __test__/validation.test.ts
     FAIL  __test__/main.test.ts
      ● Test suite failed to run

        TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
        __test__/main.test.ts:89:50 - error TS2769: No overload matches this call.
          The last overload gave the following error.
            Argument of type 'Value' is not assignable to parameter of type 'string | RegExp'.
              Type 'true' is not assignable to type 'string | RegExp'.

        89         stringified: STRINGIFIED_TYPICAL.replace(METADATA_TYPICAL.version, "Beta"),
                                                            ~~~~~~~~~~~~~~~~~~~~~~~~

          node_modules/typescript/lib/lib.es5.d.ts:454:5
            454     replace(searchValue: string | RegExp, replacer: (substring: string, ...args: any[]) => string): string;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            The last overload is declared here.

     FAIL  __test__/data.test.ts
      ● Test suite failed to run
    […]
     FAIL  __test__/functions.test.ts
      ● Test suite failed to run
    […]

    Test Suites: 3 failed, 3 passed, 6 total
    Tests:       33 passed, 33 total
    Snapshots:   0 total
    Time:        1.406s
    Ran all test suites.
    npm ERR! Test failed.  See above for more details.

    > We are not doing semantic versioning and 23.10 is a re-write, run npm i -D ts-jest@"<23.10.0" to go back to the previous version — [ts-jest](https://github.com/kulshekhar/ts-jest/tree/5f33386bade2d4d9a8efd3f53f02d5275761c8cc)

    💲 npm install --save-dev ts-jest@"<23.10.0"
    + ts-jest@23.1.4
    […]

    💲 npm test
    […]
     PASS  __test__/stringify.test.ts
     PASS  __test__/read.test.ts
     PASS  __test__/validation.test.ts
     PASS  __test__/main.test.ts
     PASS  __test__/data.test.ts
     PASS  __test__/functions.test.ts

    Test Suites: 6 passed, 6 total
    Tests:       54 passed, 54 total
    Snapshots:   0 total
    Time:        2.061s
    Ran all test suites.

I have verified that [Userscripter][us] (master and v1.5.0) and [Better
SweClockers][bsc] build and pass all tests with this version.

[us]: https://github.com/SimonAlling/userscripter
[bsc]: https://github.com/SimonAlling/better-sweclockers